---
title: "Santé humaine liée à l'obésité"
author: "Lila Franchin, Arthur Miroux, Irma Gaziaux, Quentin Dewulf"
date: "`r Sys.Date()`"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
editor: visual
lang: fr
bibliography: bibliography/references.bib
---

<!--% Complétez l'entête en définissant un titre qui soit représentatif de votre travail. Indiquez aussi les noms des auteurs. -->

<!--# Dans les différentes sections, vous trouverez des indicateurs "...Vos XXX ici..." Vous devez bien sûr REMPLACER ces indicateurs par votre propre texte. Ne les laissez pas dans votre version finale du document. Vous devez travailler dans le même document (pas question de faire un document séparé par étudiant). Gérez les conflits éventuels. -->

```{r setup, include=FALSE}
# Ceci est nécessaire pour les tests SDD, ne pas utiliser dans un "vrai" projet
if (!"tools:tests" %in% search())
  source(here::here("tests/tools_tests.R"), attach(NULL, name = "tools:tests"))

# Configuration de l'environnement SciViews::R
SciViews::R("infer", lang = "fr")
```

# Introduction

<!--% Sur base de la bibliographie (lecture de l'article fourni et de vos propres recherches sur Internet), rédigez une introduction du sujet en 3 à 4 paragraphes. Cette introduction doit guider le lecteur vers votre but. Vous devez citer vos sources, c'est-à-dire qu’il faut indiquer au minimum la référence bibliographique fournie de manière correcte (inspirez-vous de ce qui est indiqué dans le bloc-notes, mais reformulez : un simple copier-coller de l'introduction du bloc-notes n'est PAS considéré comme l'exercice réalisé !) -->

<!--# Ce projet porte sur la santé humaine liée à l'obésité, à la façon de se nourrir et aux activités réalisées (plus ou moins sédentaire ou actif) ... Réalisez des recherches bibliographiques afin d'avoir une vision précise de la thématique. Existe-t-il des indicateurs calculables pour quantifier l'état de santé d'un individu, par exemple ? Naturellement, ces indicateurs doivent être calculables sur bases des variables mesurées dans votre jeu de données. Focalisez-vous donc sur ces variables-là. -->

Selon @lebacq2015 a effectué différentes études sur l'obésité en Belgique en 2014. Des valeurs de l'OMS et de de l'IOTF indique que 45% de la population belge entre 3 ans et 64 ans a un IMC trop élevé, 29% est en sur poids et 16% est obèse. Les hommes auraient tendance à avoir un IMC plus élevé que les femmes. L'âge, de plus, aurait un impact sur l'obésité. A partir de 35 ans, un belge sur trois serait en sur poids. Selon www.louvainmedical.be, la quantité de sucres ingérée augmente le risque de prise de poids. Selon Actu-Carnet-Sommeil-Nutrition.pdf, la durée du sommeil affecte la prise de poids. La population a tendance a dormir insuffisamment, cette diminution du temps de sommeil augmente la prise du poids. D'après https://www.sciencedirect.com/science/article/pii/S1878622721000230, une activité physique régulière diminuerait la prise de poids.

Pour diversifier notre travail, nous allons nous effectuer différents indices en plus de l'IMC. Nous allons effectuer le rapport tour de taille/taille qui lui aussi augmente avec l'âge. De plus, nous effectuerons la formule de Perrault et de Monnerot Dumaine.

Le but de notre travail est de mieux comprendre l'obésité. Nous allons pouvoir déterminer si pour notre échantillon, il y a une augmentation de l'obésité avec l'âge et le sexe, le sommeil, la quantité de sucre et l'acitivité physique. Par rapport à nos mesures, nous avons réalisés des indices et différents tests. Par ces calculs, nous avons essayé de comprendre ce qui pouvait augmenter les risques d'obésité.

# But

<!--% Formulez ici de façon concise et précise votre question de recherche en 1 à 2 phrases. -->

L'impact de différents facteurs tels que l'âge ou le genre sur le risque de surpoids et l'obésité.

# Matériel et méthodes

<!--% Cette section doit comprendre une explication technique sur les mesures effectuées et sur le protocole relatif à l'acquisition des données en 3 à 4 paragraphes. Vous ajouterez aussi un paragraphe qui détaille les outils logiciels et statistiques utilisés (logiciels et versions des logiciels). Un simple copier-coller du matériel et méthodes du bloc-notes ne sera PAS considéré comme acceptable. -->

Les mesures ont été effectuées par les étudiants de deuxième année de l'UMONS. Les données mesurées ont été décidées ensemble dans un dictionnaire de données. L'encodement des données a été réalisé de sorte à assurer l'anomymat.

Nous avons effectué notre analyse des données avec le logiciel R (r R.version.string) et avec le package {inferit} version r packageVersion("inferit") dans la \[SciViews Box 2024\] (https://www.sciviews.org/software/svbox/) dans \[SaturnCloud\] (https://saturncloud.io/).

# Résultats

## Description des données

<!--% Extrayez les quelques éléments les plus pertinents (3 à 5) de votre document `human_notebook.qmd` pour décrire les données de manière cohérente par rapport au but. Reprenez les interprétations en les reformulant de manière concise pour former un texte qui se lit en continu (donc un texte plus construit que ce que vous avez indiqué dans le bloc-notes). -->

<!--# N'oubliez pas que ce document doit pouvoir compiler indépendamment du reste. Cela implique que vous ajoutiez un chunk d'importation des données et que vous recalculiez tout ce qui doit l'être... Par contre, un simple copier-coller de toute la partie résultats du bloc-notes ne sera pas considéré comme un travail réalisé : vous devez sélectionner, et éventuellement remanier un peu le code, pour ne conserver que ce qui est utile ici. -->

**1) Détails de l'échantillon**

Premièrement, nous devons mettre en évidence la qualité de notre échantillon. La majorité des participants se trouve entre 18 et 25 ans. De plus, nous avons un biais générationnel, car des tranches d'âge intermédiaires sont largement sous-représentées.

Également, notre effectif total est seulement de 144 (65 hommes et 79 femmes).

Il convient de noter que cet échantillon n'est pas représentatif de la population belge en raison d'un biais de sélection pour l'analyse de nos résultats.

**2) Différences notables entre homme/femmes**

Les principales différences observées entre les hommes et les femmes sont les suivantes :

Les hommes sont plus actifs physiquement et consomment d'avantage de fast-food et d'alcool.

Cependant, les femmes fument plus que les hommes.

**3) Dépendance entre l'age et l'IMC (Test Chi² 1)**

Nous avons montré via un test Chi² qu'il y a bel et bien une augmentation significative de l'IMC en fonction de l'âge.

Ceci était attendu, car les résultats de Thérésa Lebacq indiquait que l'IMC moyen augmente en fonction de l'âge.

**4) Indépendance entre l'IMC et la consommation de sucre (Test Chi² 2)**

Nous avons montré grâce à un test Chi² que la consommation de sucre n'a pas d'impact significatif sur le poids.

Ceci est assez surprenant car on associe généralement une consommation de sucre élevée à un IMC plus important.

**5) Pas d'impact de l'activité physique sur l'IMC (Anova à un facteur 2)**

Après avoir séparé en 4 groupes de nombre équivalent selon l'activité physique, notre test ANOVA a montré que l'activité physique n'a pas d'effet significatif sur l'IMC.

Les variances entre les groupes sont faibles par rapport aux variances au sein des groupes.

Les conditions d'application confirment notre ANOVA et le test non-paramétrique aboutit aux mêmes conclusions.

L'IMC présente des limites en tant qu'indicateur de santé. Comme il ne distingue pas la masse musculaire de la masse grasse, les sportifs pourraient bénéficier d'une évaluation différente de l'IMC.

## Tests d'hypothèses

<!--% Sélectionnez les 4 tests d'hypothèses les plus pertinents depuis `human_notebook.qmd`, ainsi bien sûr que les calculs des indices nécessaires que vous placerez juste au-dessus de vos tests. Ces tests doivent répondre à votre question de recherche (le but). Reformulez les interprétations pour former un texte qui se lit en continu. -->

1)  Test de chi carré d'indépendance, lien entre l'âge et l'IMC

Calcul de l'IMC : mass_corr/taille1\^2

-   H₀ : l'âge et l'IMC sont indépendants. 

<!-- -->

-   H₁ : l'âge et l'IMC sont dépendants.

    2\) Test t Student, comparaison de l'IMC entre les hommes et les femmes

-   H₀ : la moyenne de l'IMC chez les hommes est égale à celles de femmes

-   H₁ : la moyenne de l'IMC chez les hommes est différente à celles de femmes

    3\) Test t pour les moyennes indépendantes, effet du tabagisme sur la répartition de la graisse abdominale

    Calcul rapport taille/tour de taille (=répartition de la graisse abdominale) : rapport_tour_taille_taille = tour_taille/taille

-   H₀ : pas de différence entre les fumeurs et les non-fumeurs sur la moyenne des rapports taille/tour de taille.

-   H₁ : différence entre les fumeurs et les non-fumeurs sur la moyenne des rapports taille/tour de taille.

    4\) ANOVA à un facteur, lien entre activité physique et IMC

-   H₀ : l'IMC est le même peu importe le niveau d'heures d'activité physique.

-   H₁ : au moins une moyenne d'IMC diffère avec le nombre d'heures d'activité physique.

    Le test du chi carré révèle une dépendance significative entre l'âge et l'IMC au seuil alpha de 5 %, ce qui nous conduit à rejeter l'hypothèse d'indépendance (H₀). Cela laisse entendre que le poids a tendance à évoluer avec l'âge, un constat en accord avec la littérature scientifique, qui souligne fréquemment une prise de poids progressive au fil des années. En revanche, avec une valeur p de 0,37 (bien supérieure au seuil de 0,05), nous ne rejetons pas H₀ dans le cadre de la comparaison des IMC entre hommes et femmes. Autrement dit, il n'existe pas de différence significative entre les deux genres dans notre échantillon. (Ce résultat pourrait néanmoins être influencé par la taille réduite de l'échantillon ou par des limites méthodologiques.) Ensuite, le test effectué sur le rapport taille/tour de taille ne met pas non plus en évidence de différence significative au seuil de 5 %, ce qui suggère que le tabagisme n'a pas d'impact sur cette mesure dans notre population étudiée. Enfin, les résultats du test ANOVA ne montrent aucune différence significative entre les groupes définis selon le nombre d'heures d'activité physique par semaine. Cela indique une absence de lien clair entre niveau d'activité physique et IMC. Ce résultat contredit les nombreuses études qui démontrent les bienfaits de l'activité physique sur le poids, (mais cette divergence peut s'expliquer par la petite taille de notre échantillon ainsi que par le caractère déclaratif des données recueillies.) 

## Discussion et conclusions

<!--% Reprenez les résultats obtenus, discutez-les d'un point de vue biologique en 4 à 5 paragraphes et concluez votre travail. Vous pouvez les mettre également en relation avec vos recherches bibliographiques dans cette section. -->

...Vos conclusions ici...

<!--# Important : ce document doit compiler SANS ERREURS avec le bouton 'Rendu' sinon le travail sera sanctionné lourdement. La compilation du document Quarto est maintenant considérée comme acquise. -->

# Référence

<!--% N'indiquez rien ci-dessous. Quarto se chargera de rajouter vos références bibliographiques automatiquement. -->
